apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lqitrvfxf-go 
  janus-idp.io/tekton: lqitrvfxf-go
  backstage.io/kubernetes-id: lqitrvfxf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lqitrvfxf-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml